import { StyleSheet } from 'react-native';
import { colors, radius, shadow, spacing } from '../../styles/theme';

const styles = StyleSheet.create({
  keyboardView: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    padding: spacing.lg,
    paddingBottom: 180,
    gap: spacing.md,
  },
  header: {
    paddingTop: spacing.xl,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  title: {
    flex: 1,
    color: colors.text,
    fontSize: 29,
    lineHeight: 34,
    fontWeight: '900',
  },
  settingsButton: {
    width: 48,
    minHeight: 42,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.line,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: spacing.md,
  },
  relayTile: {
    width: '48.8%',
    aspectRatio: 1.32,
    borderRadius: radius.md,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.md,
    ...shadow,
  },
  relayOn: {
    backgroundColor: colors.green,
    borderColor: '#86EFAC',
  },
  relayOff: {
    backgroundColor: '#263244',
    borderColor: '#526173',
  },
  relayDisabled: {
    opacity: 0.45,
  },
  relayName: {
    color: colors.text,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
    textAlign: 'center',
  },
  relayState: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '900',
  },
  settings: {
    gap: spacing.md,
  },
  settingsMenu: {
    gap: spacing.sm,
  },
  settingsVersion: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    marginTop: spacing.sm,
    textAlign: 'center',
  },
  settingsMenuCard: {
    minHeight: 74,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  settingsMenuBadge: {
    width: 42,
    height: 42,
    borderRadius: radius.sm,
    backgroundColor: '#12365A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsMenuBadgeDanger: {
    backgroundColor: '#451A1A',
  },
  settingsMenuBadgeText: {
    color: colors.cyan,
    fontSize: 13,
    fontWeight: '900',
  },
  settingsMenuText: {
    flex: 1,
  },
  settingsMenuTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  settingsMenuSubtitle: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
    fontWeight: '700',
  },
  settingsMenuChevron: {
    color: colors.muted,
    fontSize: 22,
    fontWeight: '900',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  backButton: {
    minHeight: 38,
    minWidth: 72,
    borderRadius: radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceRaised,
    borderWidth: 1,
    borderColor: colors.line,
  },
  backText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  sectionTitle: {
    flex: 1,
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  settingCard: {
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    padding: spacing.md,
    gap: spacing.sm,
  },
  automationWrap: {
    gap: spacing.md,
  },
  pickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  pickerOption: {
    minHeight: 38,
    maxWidth: '48%',
    flexGrow: 1,
    flexBasis: '46%',
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    backgroundColor: '#0B111C',
  },
  activePickerOption: {
    backgroundColor: colors.blue,
    borderColor: colors.blue,
  },
  pickerOptionText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  activePickerOptionText: {
    color: colors.white,
  },
  settingTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '900',
  },
  nameInput: {
    minHeight: 48,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: '#0B111C',
    color: colors.text,
    paddingHorizontal: spacing.md,
    fontSize: 16,
    fontWeight: '800',
  },
  saveButton: {
    minHeight: 44,
    borderRadius: radius.sm,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveText: {
    color: '#06130B',
    fontWeight: '900',
  },
  scheduleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  scheduleTitleWrap: {
    flex: 1,
  },
  scheduleMeta: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  deleteScheduleButton: {
    minHeight: 38,
    minWidth: 78,
    borderRadius: radius.sm,
    backgroundColor: colors.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteScheduleText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '900',
  },
  aboutText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  empty: {
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    padding: spacing.lg,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  emptyText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: spacing.sm,
  },
  pressed: {
    opacity: 0.8,
  },
  logoutButton: {
    minHeight: 50,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.red,
  },
  logoutText: {
    color: colors.white,
    fontWeight: '900',
  },
  rudradeb: {
    color: colors.cyan,
    fontWeight: '800',
  },
  aboutTextFooter: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: spacing.md,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(5, 9, 15, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    padding: spacing.lg,
    gap: spacing.md,
  },
  repeatSection: {
    gap: spacing.sm,
  },
  repeatGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  repeatOption: {
    minHeight: 38,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    backgroundColor: '#0B111C',
  },
  activeRepeatOption: {
    backgroundColor: colors.blue,
    borderColor: colors.blue,
  },
  repeatOptionText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  activeRepeatOptionText: {
    color: colors.white,
  },
  dayGrid: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  dayButton: {
    width: 34,
    height: 34,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0B111C',
  },
  activeDayButton: {
    backgroundColor: colors.green,
    borderColor: colors.green,
  },
  dayText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  activeDayText: {
    color: '#06130B',
  },
  modalTitle: {
    color: colors.text,
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '900',
    textAlign: 'center',
  },
  modalText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  dateInput: {
    width: 58,
    minHeight: 50,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: '#0B111C',
    color: colors.text,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '900',
  },
  yearInput: {
    width: 86,
  },
  dateSeparator: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
  },
  timeInput: {
    width: 76,
    minHeight: 56,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: '#0B111C',
    color: colors.text,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '900',
  },
  timeSeparator: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
  },
  actionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  actionButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeActionButton: {
    backgroundColor: colors.blue,
    borderColor: colors.blue,
  },
  actionText: {
    color: colors.muted,
    fontWeight: '900',
  },
  activeActionText: {
    color: colors.white,
  },
  errorText: {
    color: colors.red,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  modalActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  cancelButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: {
    color: colors.text,
    fontWeight: '900',
  },
  saveScheduleButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: radius.sm,
    backgroundColor: colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveScheduleText: {
    color: '#06130B',
    fontWeight: '900',
  },
  disabledButton: {
    opacity: 0.45,
  },
  homeIcon: {
    width: 24,
    height: 22,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  homeRoof: {
    position: 'absolute',
    top: 1,
    width: 18,
    height: 18,
    borderLeftWidth: 3,
    borderTopWidth: 3,
    borderColor: colors.text,
    transform: [{ rotate: '45deg' }],
  },
  homeBody: {
    width: 18,
    height: 14,
    borderWidth: 3,
    borderTopWidth: 0,
    borderColor: colors.text,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  homeDoor: {
    width: 5,
    height: 8,
    backgroundColor: colors.text,
  },
  gearIcon: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gearCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 3,
    borderColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gearDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.text,
  },
  gearTooth: {
    position: 'absolute',
    width: 5,
    height: 5,
    borderRadius: 1,
    backgroundColor: colors.text,
  },
  gearToothTop: {
    top: 0,
  },
  gearToothRight: {
    right: 0,
  },
  gearToothBottom: {
    bottom: 0,
  },
  gearToothLeft: {
    left: 0,
  },
});

export default styles;
